# Generated by Django 2.1.7 on 2019-05-23 01:24

import croco.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField(default='Escriba su direccion..')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('No_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croco.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_pago', models.CharField(choices=[('Credito', 'Tarjeta de credito'), ('PayPal', 'Paypal')], default='Credito', max_length=40)),
                ('fecha', models.DateField(auto_now=True)),
                ('codigo_rastreo', models.CharField(default=croco.models.Pago.build_id, max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croco.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('origen', models.CharField(max_length=50)),
                ('imagen', models.ImageField(help_text='imagen real del producto', null=True, upload_to='')),
                ('precio', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croco.Productos'),
        ),
    ]
