# Generated by Django 2.1.7 on 2019-05-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.URLField(default=''),
        ),
    ]
