# Generated by Django 2.1.7 on 2019-05-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croco', '0002_auto_20190522_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='paypal_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
